import { Movie } from 'src/app/core/movies';

export let movieEntity: Partial<Movie> = {
  id: null,
  title: null,
  year: null,
  rated: null,
  released: null,
  runtime: null,
  genre: null,
  director: null,
  writer: null,
  actors: null,
  plot: null,
  language: null,
  country: null,
  awards: null,
  poster: null,
  metaScore: null,
  imdbRating: null,
  imdbVotes: null,
  imdbId: null,
  type: null,
  dvd: null,
  boxOffice: null,
  production: null,
  website: null,
};
