import { Movie } from 'src/app/core/movies';

export let movieEntity: Partial<Movie> = {
  id: null,
  title: null,
  year: null,
  rated: null,
  released: null,
  runtime: null,
  genre: null,
  director: null,
  writer: null,
  actors: null,
  plot: null,
  language: null,
  country: null,
  awards: null,
  poster: null,
  metascore: null,
  imdbrating: null,
  imdbvotes: null,
  imdbid: null,
  type: null,
  dvd: null,
  boxoffice: null,
  production: null,
  website: null,
};
